import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import { useRouter } from 'next/router'
import Charts from '../../components/ChartsContainer'


export default function CryptoHome() {
    const router = useRouter();

    const {slug} = router.query;
  return (
    <div>
      <Head>
        <title>Crypto History Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICN.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <main>
      <Charts slug={slug}/>
      </main>
    </div>
  )
}