import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto History Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICN.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <main></main>
    </div>
  )
}
